baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'paper'

# disqusShortname = 'YOUR_DISQUS_SHORTNAME'   # use disqus comments

[params]
# color style
color = 'linen'                           # linen, wheat, gray, light

# header social icons
twitter = 'YOUR_TWITTER_ID'               # twitter.com/YOUR_TWITTER_ID
github = 'YOUR_GITHUB_ID'                 # github.com/YOUR_GITHUB_ID
instagram = 'YOUR_INSTAGRAM_ID'           # instagram.com/YOUR_INSTAGRAM_ID
linkedin = 'YOUR_LINKEDIN_ID'             # linkedin.com/in/YOUR_LINKEDIN_ID
mastodon = 'YOUR_MASTODON_LINK'           # e.g. 'https://mastodon.instance/@xxx'
rss = true                                # show rss icon

# home page profile
# avatar = 'GRAVATAR_EMAIL'               # gravatar email or image url
name = 'YOUR_NAME'
bio = 'YOUR_BIO'                          # THIS IS YOUR BIO!!!


# misc
disableHLJS = true                        # disable highlight.js
monoDarkIcon = true                       # show monochrome dark mode icon
# gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
# graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)
math = false                               # enable KaTex math typesetting for a specific page

comments = false                          # disable comments for a specific page
